# Generated by Django 5.2.10 on 2026-02-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_subject_department_remove_subject_subject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subject')),
            ],
        ),
    ]
