# Generated by Django 5.2.10 on 2026-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='earned_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
