# Generated by Django 5.2.10 on 2026-02-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_marks_earned_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubject',
        ),
    ]
